#!/bin/sh -xe
 
# Title: oe-made-easy clean-build script
# Where: https://github.com/lloydchang/oe-made-easy
# Purpose: To `bitbake ...` from upstream oe-core http://www.openembedded.org/wiki/OpenEmbedded-Core
# Author: Lloyd Chang <lloyd.chang@gmail.com>
# Documentation: See README file

# capture our build host's linux distribution, kernel version, userspace architecture and username
lsb_release -a; uname -a; dpkg --print-architecture; whoami

# bootstrapping git and utilities needed by oe-core/meta/classes/sanity.bblcass
SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -A apt-get update
SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -A apt-get install -y git patch diffstat texi2html texinfo subversion bzip2 tar gzip gawk chrpath wget cpio make gcc g++

PARAMETERS=$@
# Getting Started from https://wiki.yoctoproject.org/wiki/OpenEmbedded-Core
OE_CORE_DIR=./oe-core-$(echo $PARAMETERS | sed -e "s/ /_/g")
OE_CORE_DIR_SYMLINK=./oe-core
BITBAKE_DIR=./bitbake
[ -d $OE_CORE_DIR ] && mv $OE_CORE_DIR $OE_CORE_DIR.backup.$(date "+%Y%m%dT%H%M%S")
git clone git://git.openembedded.org/openembedded-core $OE_CORE_DIR
[ [ -L $OE_CORE_DIR_SYMLINK ] -o [ -d $OE_CORE_DIR ] ] && mv $OE_CORE_DIR_SYMLINK $OE_CORE_DIR_SYMLINK.backup.$(date "+%Y%m%dT%H%M%S")
ln -sfn $OE_CORE_DIR_SYMLINK $OE_CORE_DIR
cd $OE_CORE_DIR
[ -d $BITBAKE_DIR ] && mv  $BITBAKE_DIR  $BITBAKE_DIR.backup.$(date "+%Y%m%dT%H%M%S")
git clone git://git.openembedded.org/bitbake $BITBAKE_DIR

MACHINE_LIST="qemuarm qemux86 qemux86-64"
LOCAL_CONF_FILE=./conf/local.conf
for CURRENT_MACHINE in $MACHINE_LIST
do
    set BUILD-$CURRENT_MACHINE
    . ./oe-init-build-env
    cp $LOCAL_CONF_FILE $LOCAL_CONF_FILE.backup.$(date "+%Y%m%dT%H%M%S")
    sed -i "/^#MACHINE ?= \"qemuarm\"/s/$/\\nMACHINE = \"$CURRENT_MACHINE\"/" $LOCAL_CONF_FILE
    sed -i "s/^#BB_NUMBER_THREADS.*$/BB_NUMBER_THREADS\ =\ \"$(grep -c processor /proc/cpuinfo)\"/" $LOCAL_CONF_FILE
    sed -i "s/^#PARALLEL_MAKE.*$/PARALLEL_MAKE\ =\ \"-j$(grep -c processor /proc/cpuinfo)\"/" $LOCAL_CONF_FILE
    BITBAKE_LOG_FILE=$(pwd)/bitbake.log.$(date "+%Y%m%dT%H%M%S")
    bitbake $PARAMETERS 2>&1 | tee $BITBAKE_LOG_FILE
    cd ..
done
