#!/bin/sh -xe
 
# Title: oe-getting-started clean-build script
# Purpose: To `bitbake ...` from upstream oe-core http://www.openembedded.org/wiki/OpenEmbedded-Core
# Author: Lloyd Chang <lloyd.chang@gmail.com>
# Documentation: See README file

# capture our build host's linux distribution, kernel version, userspace architecture and username
lsb_release -a
uname -a
dpkg --print-architecture
whoami

# bootstrapping git and tools needed by oe-core/meta/classes/sanity.bblcass
SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -A apt-get update
SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -A apt-get install -y git patch diffstat texi2html texinfo subversion bzip2 tar gzip gawk chrpath wget cpio make gcc g++

# Getting Started from https://wiki.yoctoproject.org/wiki/OpenEmbedded-Core
OE_CORE_DIR=./oe-core
[ -d $OE_CORE_DIR ] && mv $OE_CORE_DIR $OE_CORE_DIR.backup.$(date "+%Y%m%dT%H%M%S")
git clone git://git.openembedded.org/openembedded-core $OE_CORE_DIR
cd $OE_CORE_DIR
BITBAKE_DIR=./bitbake
[ -d $BITBAKE_DIR ] && mv  $BITBAKE_DIR  $BITBAKE_DIR.backup.$(date "+%Y%m%dT%H%M%S")
git clone git://git.openembedded.org/bitbake $BITBAKE_DIR

PARAMETERS=$@
MACHINE_LIST="qemuarm qemux86 qemux86-64"
LOCAL_CONF_FILE=./conf/local.conf
for CURRENT_MACHINE in $MACHINE_LIST
do
    set BUILD-$CURRENT_MACHINE
    . ./oe-init-build-env
    cp $LOCAL_CONF_FILE $LOCAL_CONF_FILE.backup.$(date "+%Y%m%dT%H%M%S")
    sed -i "/^#MACHINE ?= \"qemuarm\"/s/$/\\nMACHINE = \"$CURRENT_MACHINE\"/" $LOCAL_CONF_FILE
    sed -i "s/^#BB_NUMBER_THREADS.*$/BB_NUMBER_THREADS\ =\ \"$(grep -c processor /proc/cpuinfo)\"/" $LOCAL_CONF_FILE
    sed -i "s/^#PARALLEL_MAKE.*$/PARALLEL_MAKE\ =\ \"-j$(grep -c processor /proc/cpuinfo)\"/" $LOCAL_CONF_FILE
    bitbake $PARAMETERS
    cd ..
done
